/** 引用格式化真源入口（三端复用）：见 ./format.ts 顶部说明。 */
export type { CitationAuthorInput, CitationAuthorLike, CitationPaperLike } from './types.ts';
export {
  cleanPart,
  initialsCompact,
  initialsWithDots,
  isCjkName,
  isCjkText,
  joinParts,
  trimTrailingPeriod,
} from './text.ts';
export {
  CITATION_STYLES,
  CITATION_STYLE_IDS,
  DEFAULT_CITATION_STYLE,
  citationStyleKind,
  getCitationStyle,
  isCitationStyleId,
  isNumericCitationStyle,
  normalizeCitationStyle,
  type CitationStyleDescriptor,
  type CitationStyleId,
  type CitationStyleKind,
} from './styles.ts';
export {
  assignCitationNumbers,
  formatNumberRanges,
  normalizeCitationItem,
  normalizeCitationItems,
  type CitationItemInput,
} from './numbering.ts';
export {
  BIBLIOGRAPHY_CONTROL_TAG,
  BIBLIOGRAPHY_CONTROL_TITLE,
  CITATION_CONTROL_TAG_PREFIX,
  CITATION_CONTROL_TITLE,
  DEFAULT_BIBLIOGRAPHY_TITLE,
  DOCUMENT_SCHEMA_VERSION,
  DOCUMENT_SETTINGS_KEYS,
  createCitationId,
  encodeCitationControlTag,
  extractCitationControlTagsFromOoxml,
  extractBibliographyTagCount,
  findStoredCitation,
  hasBibliographyControlInOoxml,
  isBibliographyControlTag,
  isCitationControlTag,
  normalizeStoredCitations,
  parseCitationControlTag,
  removeStoredCitation,
  serializeStoredCitations,
  upsertStoredCitation,
  type StoredCitation,
} from './documentTags.ts';
export {
  apaAuthorName,
  authorDateLabel,
  deriveNameParts,
  formatApa7,
  formatAuthorsApa,
  formatAuthorsGbt,
  formatAuthorsGbt87,
  formatAuthorsIeee,
  formatBibliographyEntry,
  formatBibliographyLines,
  formatGbt87Entry,
  formatGbtEntry,
  formatIeee,
  formatInlineApaCitation,
  gbt87AuthorName,
  gbt87DocumentMark,
  gbtAuthorName,
  gbtDocumentMark,
  ieeeAuthorName,
  normalizeGbt87Punctuation,
  normalizeRenderGroups,
  paperAuthorParts,
  renderCitations,
  toAuthorParts,
  wrapAffixes,
  type AuthorParts,
  type CitationRenderEntry,
  type CitationRenderGroup,
  type CitationRenderRequest,
  type CitationRenderResult,
  type Gbt87Punctuation,
} from './format.ts';
export {
  formatAuthorDateSegments,
  formatNumericSegments,
  numberRanges,
  segmentsToText,
  type CitationSegment,
} from './format.ts';
export {
  BIBLIOGRAPHY_PARAGRAPH_STYLE_ID,
  BIBLIOGRAPHY_PARAGRAPH_STYLE_NAME,
  BOOKMARK_PREFIX,
  assignBookmarkNames,
  bookmarkIdBase,
  bookmarkNameFor,
  buildBibliographyPackage,
  buildBibliographyParagraphs,
  buildInlineCitationPackage,
  buildInlineCitationRuns,
  escapeXmlText,
  fnv1aBase36,
  isPaperQuayBookmarkName,
  wrapPackage,
  type BibliographyEntryInput,
  type BibliographyOoxmlOptions,
  type InlineCitationOptions,
} from './wordOoxml.ts';
export {
  DEFAULT_PREFS,
  DOCUMENT_MODEL_NAMESPACE,
  DOCUMENT_MODEL_SCHEMA_VERSION,
  MODEL_FALLBACK_SETTING_KEY,
  SCHEMA_VERSION_SETTING_KEY,
  V1_SETTING_KEYS,
  applyDuplicateSplit,
  citedPaperIds,
  createDocumentId,
  createEmptyModel,
  diffRender,
  findCitation,
  keepManualEdit,
  migrateV1Settings,
  normalizeControlText,
  normalizeModel,
  normalizePrefs,
  parseModelXml,
  pickLatestModel,
  planDuplicateSplit,
  planRender,
  pruneModel,
  recordRendered,
  removeCitation,
  serializeModelXml,
  snapshotResolver,
  upsertCitation,
  upsertSnapshots,
  type CitationDiff,
  type CitationOutput,
  type DocumentCitation,
  type DocumentModel,
  type DocumentPrefs,
  type DuplicateSplit,
  type ItemSnapshot,
  type ManualEdit,
  type RenderPlan,
  type RenderPlanOptions,
} from './documentModel.ts';
