/** 引用格式化真源入口（三端复用）：见 ./format.ts 顶部说明。 */
export type { CitationAuthorInput, CitationAuthorLike, CitationPaperLike } from './types.ts';
export {
  cleanPart,
  initialsCompact,
  initialsWithDots,
  isCjkName,
  isCjkText,
  joinParts,
  trimTrailingPeriod,
} from './text.ts';
export {
  CITATION_STYLES,
  CITATION_STYLE_IDS,
  DEFAULT_CITATION_STYLE,
  citationStyleKind,
  getCitationStyle,
  isCitationStyleId,
  isNumericCitationStyle,
  normalizeCitationStyle,
  type CitationStyleDescriptor,
  type CitationStyleId,
  type CitationStyleKind,
} from './styles.ts';
export {
  assignCitationNumbers,
  formatNumberRanges,
  normalizeCitationItem,
  normalizeCitationItems,
  type CitationItemInput,
} from './numbering.ts';
export {
  BIBLIOGRAPHY_CONTROL_TAG,
  BIBLIOGRAPHY_CONTROL_TITLE,
  CITATION_CONTROL_TAG_PREFIX,
  CITATION_CONTROL_TITLE,
  DEFAULT_BIBLIOGRAPHY_TITLE,
  DOCUMENT_SCHEMA_VERSION,
  DOCUMENT_SETTINGS_KEYS,
  createCitationId,
  encodeCitationControlTag,
  extractCitationControlTagsFromOoxml,
  extractBibliographyTagCount,
  findStoredCitation,
  hasBibliographyControlInOoxml,
  isBibliographyControlTag,
  isCitationControlTag,
  normalizeStoredCitations,
  parseCitationControlTag,
  removeStoredCitation,
  serializeStoredCitations,
  upsertStoredCitation,
  type StoredCitation,
} from './documentTags.ts';
export {
  apaAuthorName,
  authorDateLabel,
  deriveNameParts,
  formatApa7,
  formatAuthorsApa,
  formatAuthorsGbt,
  formatAuthorsIeee,
  formatBibliographyEntry,
  formatBibliographyLines,
  formatGbtEntry,
  formatIeee,
  formatInlineApaCitation,
  gbtAuthorName,
  gbtDocumentMark,
  ieeeAuthorName,
  normalizeRenderGroups,
  paperAuthorParts,
  renderCitations,
  toAuthorParts,
  wrapAffixes,
  type AuthorParts,
  type CitationRenderEntry,
  type CitationRenderGroup,
  type CitationRenderRequest,
  type CitationRenderResult,
} from './format.ts';
